Use print function to avoid escaping issues.
When cursor is over code like the following:

    Template.Foo.events({ "change select[name='xyz']": bar });

it leads to the following stack trace because the plugin doesn't escape strings
properly:

    Error detected while processing function tern#LookupArgumentHints:
    line   14:
    Traceback (most recent call last):
    Error detected while processing function tern#LookupArgumentHints:
    line   14:
      File "<string>", line 1, in <module>
    Error detected while processing function tern#LookupArgumentHints:
    line   14:
      File "[...]/tern_for_vim/script/tern.py", line 318, in tern_lookupType
    Error detected while processing function tern#LookupArgumentHints:
    line   14:
        if data: tern_echoWrap(data.get("type", ""))
    Error detected while processing function tern#LookupArgumentHints:
    line   14:
      File "[...]/tern_for_vim/script/tern.py", line 314, in tern_echoWrap
    Error detected while processing function tern#LookupArgumentHints:
    line   14:
        vim.command("echo '{0}'".format(text))
    Error detected while processing function tern#LookupArgumentHints:
    line   14:
    vim.error: Vim(echo):E121: Undefined variable: xyz